name: CI Pipeline

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar testes
        run: echo "Executando testes..."

      - name: Gerar relatório
        run: |
          mkdir reports
          echo "Relatório de testes executado com sucesso" > reports/report.txt

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: reports/